//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.autenticacao;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anuncios.ws.autenticacao package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anuncios.ws.autenticacao
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistarUtilizadorRequest }
     * 
     */
    public RegistarUtilizadorRequest createRegistarUtilizadorRequest() {
        return new RegistarUtilizadorRequest();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link UtilizadorLogin }
     * 
     */
    public UtilizadorLogin createUtilizadorLogin() {
        return new UtilizadorLogin();
    }

    /**
     * Create an instance of {@link LogoutRequest }
     * 
     */
    public LogoutRequest createLogoutRequest() {
        return new LogoutRequest();
    }

    /**
     * Create an instance of {@link LogoutResponse }
     * 
     */
    public LogoutResponse createLogoutResponse() {
        return new LogoutResponse();
    }

    /**
     * Create an instance of {@link ValidarTicketResponse }
     * 
     */
    public ValidarTicketResponse createValidarTicketResponse() {
        return new ValidarTicketResponse();
    }

    /**
     * Create an instance of {@link UtilizadorTicket }
     * 
     */
    public UtilizadorTicket createUtilizadorTicket() {
        return new UtilizadorTicket();
    }

    /**
     * Create an instance of {@link ReplicacaoResponse }
     * 
     */
    public ReplicacaoResponse createReplicacaoResponse() {
        return new ReplicacaoResponse();
    }

    /**
     * Create an instance of {@link PegarTodosUtilizadoresRequest }
     * 
     */
    public PegarTodosUtilizadoresRequest createPegarTodosUtilizadoresRequest() {
        return new PegarTodosUtilizadoresRequest();
    }

    /**
     * Create an instance of {@link PegarTodosUtilizadoresResponse }
     * 
     */
    public PegarTodosUtilizadoresResponse createPegarTodosUtilizadoresResponse() {
        return new PegarTodosUtilizadoresResponse();
    }

    /**
     * Create an instance of {@link UtilizadorRegisto }
     * 
     */
    public UtilizadorRegisto createUtilizadorRegisto() {
        return new UtilizadorRegisto();
    }

    /**
     * Create an instance of {@link ConsultarSaldoRequest }
     * 
     */
    public ConsultarSaldoRequest createConsultarSaldoRequest() {
        return new ConsultarSaldoRequest();
    }

    /**
     * Create an instance of {@link ConsultarSaldoResponse }
     * 
     */
    public ConsultarSaldoResponse createConsultarSaldoResponse() {
        return new ConsultarSaldoResponse();
    }

    /**
     * Create an instance of {@link UtilizadorRegistoReplicacaoRequest }
     * 
     */
    public UtilizadorRegistoReplicacaoRequest createUtilizadorRegistoReplicacaoRequest() {
        return new UtilizadorRegistoReplicacaoRequest();
    }

    /**
     * Create an instance of {@link ActualizacaoUtilizadorReplicacaoRequest }
     * 
     */
    public ActualizacaoUtilizadorReplicacaoRequest createActualizacaoUtilizadorReplicacaoRequest() {
        return new ActualizacaoUtilizadorReplicacaoRequest();
    }

}
