spring.application.name=authanuncioslocbd
#== LOCAL
spring.datasource.url=jdbc:mysql://localhost:3306/authanuncioslocbd
spring.datasource.username=admin
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
server.port=8083
logging.level.org.springframework.ws.server=DEBUG
logging.level.org.springframework.ws.server.endpoint=DEBUG
logging.level.org.springframework.ws=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.sent=TRACE
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE

