//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.08 at 04:01:32 PM WAT 
//


package com.anuncios.ws.autenticacao;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UtilizadorRegistoReplicacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UtilizadorRegistoReplicacao"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nome" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="telefone" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="saldo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="role" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idPerfilActivo" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="nomePerfilActivo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataCriacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataActualizacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UtilizadorRegistoReplicacao", propOrder = {
    "uuid",
    "nome",
    "email",
    "telefone",
    "saldo",
    "role",
    "idPerfilActivo",
    "nomePerfilActivo",
    "dataCriacao",
    "dataActualizacao"
})
public class UtilizadorRegistoReplicacao {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String nome;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(required = true)
    protected String telefone;
    protected int saldo;
    @XmlElement(required = true)
    protected String role;
    protected int idPerfilActivo;
    @XmlElement(required = true)
    protected String nomePerfilActivo;
    @XmlElement(required = true)
    protected String dataCriacao;
    @XmlElement(required = true)
    protected String dataActualizacao;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuid(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the telefone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefone() {
        return telefone;
    }

    /**
     * Sets the value of the telefone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefone(String value) {
        this.telefone = value;
    }

    /**
     * Gets the value of the saldo property.
     * 
     */
    public int getSaldo() {
        return saldo;
    }

    /**
     * Sets the value of the saldo property.
     * 
     */
    public void setSaldo(int value) {
        this.saldo = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the idPerfilActivo property.
     * 
     */
    public int getIdPerfilActivo() {
        return idPerfilActivo;
    }

    /**
     * Sets the value of the idPerfilActivo property.
     * 
     */
    public void setIdPerfilActivo(int value) {
        this.idPerfilActivo = value;
    }

    /**
     * Gets the value of the nomePerfilActivo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePerfilActivo() {
        return nomePerfilActivo;
    }

    /**
     * Sets the value of the nomePerfilActivo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePerfilActivo(String value) {
        this.nomePerfilActivo = value;
    }

    /**
     * Gets the value of the dataCriacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCriacao() {
        return dataCriacao;
    }

    /**
     * Sets the value of the dataCriacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCriacao(String value) {
        this.dataCriacao = value;
    }

    /**
     * Gets the value of the dataActualizacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataActualizacao() {
        return dataActualizacao;
    }

    /**
     * Sets the value of the dataActualizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataActualizacao(String value) {
        this.dataActualizacao = value;
    }

}
