spring.application.name=AnuncuiosLoc
#== LOcal
spring.datasource.url=jdbc:mysql://localhost:3308/bdinfra1
spring.datasource.username=admin
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
server.port=8084
logging.level.org.springframework.ws.server=DEBUG
logging.level.org.springframework.ws.server.endpoint=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.sent=TRACE
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
logging.level.org.springframework.ws.client.MessageTracing.sent=TRACE
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws=DEBUG
logging.level.org.springframework.ws.server.endpoint.adapter=DEBUG
