//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.perfil;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anuncios.ws.perfil package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anuncios.ws.perfil
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistarPerfilRequest }
     * 
     */
    public RegistarPerfilRequest createRegistarPerfilRequest() {
        return new RegistarPerfilRequest();
    }

    /**
     * Create an instance of {@link RegistarPerfilResponse }
     * 
     */
    public RegistarPerfilResponse createRegistarPerfilResponse() {
        return new RegistarPerfilResponse();
    }

    /**
     * Create an instance of {@link PerfilRegisto }
     * 
     */
    public PerfilRegisto createPerfilRegisto() {
        return new PerfilRegisto();
    }

    /**
     * Create an instance of {@link PegarTodosPerfilRequest }
     * 
     */
    public PegarTodosPerfilRequest createPegarTodosPerfilRequest() {
        return new PegarTodosPerfilRequest();
    }

    /**
     * Create an instance of {@link PegarTodosPerfilResponse }
     * 
     */
    public PegarTodosPerfilResponse createPegarTodosPerfilResponse() {
        return new PegarTodosPerfilResponse();
    }

    /**
     * Create an instance of {@link AssociarPerfilRequest }
     * 
     */
    public AssociarPerfilRequest createAssociarPerfilRequest() {
        return new AssociarPerfilRequest();
    }

    /**
     * Create an instance of {@link AssociarPerfilResponse }
     * 
     */
    public AssociarPerfilResponse createAssociarPerfilResponse() {
        return new AssociarPerfilResponse();
    }

    /**
     * Create an instance of {@link PegarPerfisAssociadoRequest }
     * 
     */
    public PegarPerfisAssociadoRequest createPegarPerfisAssociadoRequest() {
        return new PegarPerfisAssociadoRequest();
    }

    /**
     * Create an instance of {@link PegarPerfisAssociadoResponse }
     * 
     */
    public PegarPerfisAssociadoResponse createPegarPerfisAssociadoResponse() {
        return new PegarPerfisAssociadoResponse();
    }

}
