//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.02 at 10:20:53 PM BST 
//


package com.anuncios.ws.local;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnuncioRegisto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnuncioRegisto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idLocal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="local" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rolePolitica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uuidCriador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="nomeCriador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="emailCriador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataCriacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataActualizacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="perfis" type="{http://ws.anuncios.com/local}PoliticaRLPerfilRegisto" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnuncioRegisto", propOrder = {
    "id",
    "titulo",
    "descricao",
    "idLocal",
    "local",
    "rolePolitica",
    "uuidCriador",
    "nomeCriador",
    "emailCriador",
    "dataCriacao",
    "dataActualizacao",
    "perfis"
})
public class AnuncioRegisto {

    protected int id;
    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String descricao;
    protected int idLocal;
    @XmlElement(required = true)
    protected String local;
    @XmlElement(required = true)
    protected String rolePolitica;
    @XmlElement(required = true)
    protected String uuidCriador;
    @XmlElement(required = true)
    protected String nomeCriador;
    @XmlElement(required = true)
    protected String emailCriador;
    @XmlElement(required = true)
    protected String dataCriacao;
    @XmlElement(required = true)
    protected String dataActualizacao;
    protected List<PoliticaRLPerfilRegisto> perfis;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the idLocal property.
     * 
     */
    public int getIdLocal() {
        return idLocal;
    }

    /**
     * Sets the value of the idLocal property.
     * 
     */
    public void setIdLocal(int value) {
        this.idLocal = value;
    }

    /**
     * Gets the value of the local property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocal() {
        return local;
    }

    /**
     * Sets the value of the local property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocal(String value) {
        this.local = value;
    }

    /**
     * Gets the value of the rolePolitica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolePolitica() {
        return rolePolitica;
    }

    /**
     * Sets the value of the rolePolitica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolePolitica(String value) {
        this.rolePolitica = value;
    }

    /**
     * Gets the value of the uuidCriador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidCriador() {
        return uuidCriador;
    }

    /**
     * Sets the value of the uuidCriador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidCriador(String value) {
        this.uuidCriador = value;
    }

    /**
     * Gets the value of the nomeCriador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeCriador() {
        return nomeCriador;
    }

    /**
     * Sets the value of the nomeCriador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeCriador(String value) {
        this.nomeCriador = value;
    }

    /**
     * Gets the value of the emailCriador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailCriador() {
        return emailCriador;
    }

    /**
     * Sets the value of the emailCriador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailCriador(String value) {
        this.emailCriador = value;
    }

    /**
     * Gets the value of the dataCriacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCriacao() {
        return dataCriacao;
    }

    /**
     * Sets the value of the dataCriacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCriacao(String value) {
        this.dataCriacao = value;
    }

    /**
     * Gets the value of the dataActualizacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataActualizacao() {
        return dataActualizacao;
    }

    /**
     * Sets the value of the dataActualizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataActualizacao(String value) {
        this.dataActualizacao = value;
    }

    /**
     * Gets the value of the perfis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the perfis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerfis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoliticaRLPerfilRegisto }
     * 
     * 
     */
    public List<PoliticaRLPerfilRegisto> getPerfis() {
        if (perfis == null) {
            perfis = new ArrayList<PoliticaRLPerfilRegisto>();
        }
        return this.perfis;
    }

}
