//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.07.02 at 10:20:53 PM BST 
//


package com.anuncios.ws.local;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idLocal" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="rolePolitica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uuidCriador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="perfis" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titulo",
    "descricao",
    "idLocal",
    "rolePolitica",
    "uuidCriador",
    "perfis"
})
@XmlRootElement(name = "AnuncioRequest")
public class AnuncioRequest {

    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String descricao;
    protected int idLocal;
    @XmlElement(required = true)
    protected String rolePolitica;
    @XmlElement(required = true)
    protected String uuidCriador;
    @XmlElement(type = Integer.class)
    protected List<Integer> perfis;

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the idLocal property.
     * 
     */
    public int getIdLocal() {
        return idLocal;
    }

    /**
     * Sets the value of the idLocal property.
     * 
     */
    public void setIdLocal(int value) {
        this.idLocal = value;
    }

    /**
     * Gets the value of the rolePolitica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolePolitica() {
        return rolePolitica;
    }

    /**
     * Sets the value of the rolePolitica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolePolitica(String value) {
        this.rolePolitica = value;
    }

    /**
     * Gets the value of the uuidCriador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidCriador() {
        return uuidCriador;
    }

    /**
     * Sets the value of the uuidCriador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidCriador(String value) {
        this.uuidCriador = value;
    }

    /**
     * Gets the value of the perfis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the perfis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerfis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getPerfis() {
        if (perfis == null) {
            perfis = new ArrayList<Integer>();
        }
        return this.perfis;
    }

}
