//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.local;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LeitorRegisto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LeitorRegisto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="idAnuncio" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="uuidLeitor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataLeitura" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeitorRegisto", propOrder = {
    "id",
    "idAnuncio",
    "uuidLeitor",
    "dataLeitura"
})
public class LeitorRegisto {

    protected int id;
    protected int idAnuncio;
    @XmlElement(required = true)
    protected String uuidLeitor;
    @XmlElement(required = true)
    protected String dataLeitura;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the idAnuncio property.
     * 
     */
    public int getIdAnuncio() {
        return idAnuncio;
    }

    /**
     * Sets the value of the idAnuncio property.
     * 
     */
    public void setIdAnuncio(int value) {
        this.idAnuncio = value;
    }

    /**
     * Gets the value of the uuidLeitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidLeitor() {
        return uuidLeitor;
    }

    /**
     * Sets the value of the uuidLeitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidLeitor(String value) {
        this.uuidLeitor = value;
    }

    /**
     * Gets the value of the dataLeitura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataLeitura() {
        return dataLeitura;
    }

    /**
     * Sets the value of the dataLeitura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataLeitura(String value) {
        this.dataLeitura = value;
    }

}
