//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.local;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.anuncios.ws.local package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.anuncios.ws.local
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegistarLocalRequest }
     * 
     */
    public RegistarLocalRequest createRegistarLocalRequest() {
        return new RegistarLocalRequest();
    }

    /**
     * Create an instance of {@link RegistarLocalResponse }
     * 
     */
    public RegistarLocalResponse createRegistarLocalResponse() {
        return new RegistarLocalResponse();
    }

    /**
     * Create an instance of {@link LocalRegisto }
     * 
     */
    public LocalRegisto createLocalRegisto() {
        return new LocalRegisto();
    }

    /**
     * Create an instance of {@link PegarTodosLocaisRequest }
     * 
     */
    public PegarTodosLocaisRequest createPegarTodosLocaisRequest() {
        return new PegarTodosLocaisRequest();
    }

    /**
     * Create an instance of {@link PegarTodosLocaisResponse }
     * 
     */
    public PegarTodosLocaisResponse createPegarTodosLocaisResponse() {
        return new PegarTodosLocaisResponse();
    }

    /**
     * Create an instance of {@link AnuncioRequest }
     * 
     */
    public AnuncioRequest createAnuncioRequest() {
        return new AnuncioRequest();
    }

    /**
     * Create an instance of {@link AnuncioResponse }
     * 
     */
    public AnuncioResponse createAnuncioResponse() {
        return new AnuncioResponse();
    }

    /**
     * Create an instance of {@link AnuncioRegisto }
     * 
     */
    public AnuncioRegisto createAnuncioRegisto() {
        return new AnuncioRegisto();
    }

    /**
     * Create an instance of {@link PegarAnunciosDoUsuarioRequest }
     * 
     */
    public PegarAnunciosDoUsuarioRequest createPegarAnunciosDoUsuarioRequest() {
        return new PegarAnunciosDoUsuarioRequest();
    }

    /**
     * Create an instance of {@link TodosAnunciosResponseInfra }
     * 
     */
    public TodosAnunciosResponseInfra createTodosAnunciosResponseInfra() {
        return new TodosAnunciosResponseInfra();
    }

    /**
     * Create an instance of {@link AnuncioRegistoInfra }
     * 
     */
    public AnuncioRegistoInfra createAnuncioRegistoInfra() {
        return new AnuncioRegistoInfra();
    }

    /**
     * Create an instance of {@link PegarAnunciosDoLocalRequest }
     * 
     */
    public PegarAnunciosDoLocalRequest createPegarAnunciosDoLocalRequest() {
        return new PegarAnunciosDoLocalRequest();
    }

    /**
     * Create an instance of {@link PegarAnunciosPorCoordenadasRequest }
     * 
     */
    public PegarAnunciosPorCoordenadasRequest createPegarAnunciosPorCoordenadasRequest() {
        return new PegarAnunciosPorCoordenadasRequest();
    }

    /**
     * Create an instance of {@link LerAnuncioRequest }
     * 
     */
    public LerAnuncioRequest createLerAnuncioRequest() {
        return new LerAnuncioRequest();
    }

    /**
     * Create an instance of {@link LerAnuncioResponse }
     * 
     */
    public LerAnuncioResponse createLerAnuncioResponse() {
        return new LerAnuncioResponse();
    }

    /**
     * Create an instance of {@link LeitorRegisto }
     * 
     */
    public LeitorRegisto createLeitorRegisto() {
        return new LeitorRegisto();
    }

    /**
     * Create an instance of {@link PegarTodosAnunciosInfraResponse }
     * 
     */
    public PegarTodosAnunciosInfraResponse createPegarTodosAnunciosInfraResponse() {
        return new PegarTodosAnunciosInfraResponse();
    }

    /**
     * Create an instance of {@link PegarTodosAnunciosInfraRegisto }
     * 
     */
    public PegarTodosAnunciosInfraRegisto createPegarTodosAnunciosInfraRegisto() {
        return new PegarTodosAnunciosInfraRegisto();
    }

    /**
     * Create an instance of {@link PoliticaRLPerfilRegisto }
     * 
     */
    public PoliticaRLPerfilRegisto createPoliticaRLPerfilRegisto() {
        return new PoliticaRLPerfilRegisto();
    }

    /**
     * Create an instance of {@link AnuncioInfraResponse }
     * 
     */
    public AnuncioInfraResponse createAnuncioInfraResponse() {
        return new AnuncioInfraResponse();
    }

    /**
     * Create an instance of {@link PegarTodosAnunciosInfraRequest }
     * 
     */
    public PegarTodosAnunciosInfraRequest createPegarTodosAnunciosInfraRequest() {
        return new PegarTodosAnunciosInfraRequest();
    }

}
