//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.local;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PegarTodosAnunciosInfraRegisto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PegarTodosAnunciosInfraRegisto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="titulo" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="uuidCriador" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="rolePolitica" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataCriacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="dataActualizacao" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PegarTodosAnunciosInfraRegisto", propOrder = {
    "id",
    "titulo",
    "descricao",
    "uuidCriador",
    "rolePolitica",
    "dataCriacao",
    "dataActualizacao"
})
public class PegarTodosAnunciosInfraRegisto {

    protected int id;
    @XmlElement(required = true)
    protected String titulo;
    @XmlElement(required = true)
    protected String descricao;
    @XmlElement(required = true)
    protected String uuidCriador;
    @XmlElement(required = true)
    protected String rolePolitica;
    @XmlElement(required = true)
    protected String dataCriacao;
    @XmlElement(required = true)
    protected String dataActualizacao;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the titulo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitulo() {
        return titulo;
    }

    /**
     * Sets the value of the titulo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitulo(String value) {
        this.titulo = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the uuidCriador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUuidCriador() {
        return uuidCriador;
    }

    /**
     * Sets the value of the uuidCriador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUuidCriador(String value) {
        this.uuidCriador = value;
    }

    /**
     * Gets the value of the rolePolitica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRolePolitica() {
        return rolePolitica;
    }

    /**
     * Sets the value of the rolePolitica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRolePolitica(String value) {
        this.rolePolitica = value;
    }

    /**
     * Gets the value of the dataCriacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataCriacao() {
        return dataCriacao;
    }

    /**
     * Sets the value of the dataCriacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataCriacao(String value) {
        this.dataCriacao = value;
    }

    /**
     * Gets the value of the dataActualizacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataActualizacao() {
        return dataActualizacao;
    }

    /**
     * Sets the value of the dataActualizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataActualizacao(String value) {
        this.dataActualizacao = value;
    }

}
