//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.06.24 at 06:03:59 PM BST 
//


package com.anuncios.ws.local;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PoliticaRLPerfilRegisto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PoliticaRLPerfilRegisto"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="idAnuncio" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="idPerfil" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="nomePerfil" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PoliticaRLPerfilRegisto", propOrder = {
    "id",
    "idAnuncio",
    "idPerfil",
    "nomePerfil"
})
public class PoliticaRLPerfilRegisto {

    protected int id;
    protected int idAnuncio;
    protected int idPerfil;
    @XmlElement(required = true)
    protected String nomePerfil;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the idAnuncio property.
     * 
     */
    public int getIdAnuncio() {
        return idAnuncio;
    }

    /**
     * Sets the value of the idAnuncio property.
     * 
     */
    public void setIdAnuncio(int value) {
        this.idAnuncio = value;
    }

    /**
     * Gets the value of the idPerfil property.
     * 
     */
    public int getIdPerfil() {
        return idPerfil;
    }

    /**
     * Sets the value of the idPerfil property.
     * 
     */
    public void setIdPerfil(int value) {
        this.idPerfil = value;
    }

    /**
     * Gets the value of the nomePerfil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomePerfil() {
        return nomePerfil;
    }

    /**
     * Sets the value of the nomePerfil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomePerfil(String value) {
        this.nomePerfil = value;
    }

}
